[package]
name = "rs-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.8.1"
engine = { git = "https://github.com/Raymi306/rs-game-engine" }
